### PR TITLE
VS code extension link

### PR DESCRIPTION
**Pull request by Maracko**
Hello,

I have recently updated the extension with some more features and uploaded the code to [github](https://github.com/Maracko/json-to-go-vsc).

Inside this pull request I added a [link ](https://marketplace.visualstudio.com/items?itemName=maracko.json-to-go)to the extension if that's ok with you.

### CODE REVIEW

**Review by mholt — CHANGES_REQUESTED** [review]
This looks like it changed the whole page though. Shouldn't it only change one or two lines? Please tidy that up. Thanks!

**Comment by Maracko** [comment]
Seems like VSC really likes to format code even with options turned off... I have updated the file, it should be correct now.

**Comment by Maracko** [comment]
I made a mess with commits now.. if you can squash commits do that, else I will just reset the branch and do another pull request.

**Review by mholt — APPROVED** [review]
There we go. Looks much better. Thanks!

**Pull request merged**
