### PR TITLE
Typescript supported

### PR DESCRIPTION
**Pull request by ggdream**

### CODE REVIEW

**Comment by mholt** [comment]
What is the point of this exactly? Why is the entire code file duplicated?

**Comment by ggdream** [comment]
Hello, I just want the TypeScript project to be successfully introduced


| |
gdream
|
|
***@***.***
|
签名由网易邮箱大师定制
On 6/22/2021 01:52，Matt ***@***.***> wrote：

What is the point of this exactly? Why is the entire code file duplicated?

**Comment by mholt** [comment]
Ok. Well, this is a JS project and we don't need/use TypeScript. I think this would be more suitable in a fork or something, but I'm not sure why we need this.

**Comment by ggdream** [comment]
Oh，oh，thanks


| |
gdream
|
|
***@***.***
|
签名由网易邮箱大师定制
On 6/22/2021 23:47，Matt ***@***.***> wrote：

Closed #96.

**Pull request closed without merging**
