### PR TITLE
optionally emits "example" annotation now

### PR DESCRIPTION
**Pull request by brock-weaver-roostify**
added test cases as well

### CODE REVIEW

**Comment by brock-weaver-roostify** [comment]
added strict type check, my bad

**Comment by mholt** [comment]
What is this, exactly?

**Comment by brock-weaver-roostify** [comment]
This was an enhancement I needed for my purposes -- I had an example json payload and I wanted the values in that example to be emitted in the generated model definition.  The "example" annotation alongside the "json" annotation is picked up by https://github.com/swaggo/gin-swagger when generating Swagger documentation.

e.g. I had this:
{
  "firstName":"Alice"
}

and I wanted this go model to be emitted:
type AutoGenerated struct {
  FirstName `json:"firstName" example:"Alice"`
} 

gin-swagger uses the "example" annotation there and will include it in the resulting swagger file it generates when running "swag init".

**Comment by mholt** [comment]
Oh I see, #101. (Somehow missed that.)

Seems to be a simple enough change. Thanks for the contribution.

**Comment by brock-weaver-roostify** [comment]
Oh sorry -- I should have tagged #101 on that.  My bad.  And thank you for such a useful tool!

**Review by mholt — APPROVED** [review]

**Pull request merged**
