### PR TITLE
build dist app.js

### PR DESCRIPTION
**Pull request by YaroslavPodorvanov**

### CODE REVIEW

**Comment by YaroslavPodorvanov** [comment]
`package.json` & `webpack.config.js` need to build `app.js`

`json-to-go.test.js` need to be sure that jsonToGo work fine

i did minimal changes to optimize, that matter

**Comment by mholt** [comment]
app.js is something new. Let's just keep things the same, but remove the parts of highlight.js that we don't need.

**Comment by YaroslavPodorvanov** [comment]
`app.js is something new`, yes, `app.js` is build of other needest file

you can build `app.js` yourself with
```bash
rm -rf ./dist
npm install -D
npm run build
```

**Comment by mholt** [comment]
Sorry, but this works fine without npm as-is. I'll close this unless we can find a way to slim it down without, ironically, adding heavy dependencies.

**Comment by YaroslavPodorvanov** [comment]
I only transform already added html-direct dependencies to npm-direct dependencies, without any new dependencies, as for me webpack-npm is right way

I will try solve other issues in this project, and maybe you'll change your mind

**Comment by mholt** [comment]
I just like to keep things simple. This project doesn't need all the fancy tooling. It's just a few JS files (some minified) that a static HTML page uses.

**Pull request closed without merging**
